export const FETCH_WEATHER = 'FETCH_WEATHER'
export type FETCH_WEATHER = typeof FETCH_WEATHER

export const FETCH_WEATHER_REQUESTED = 'FETCH_WEATHER_REQUESTED'
export type FETCH_WEATHER_REQUESTED = typeof FETCH_WEATHER_REQUESTED

export const FETCH_WEATHER_SUCCEEDED = 'FETCH_WEATHER_SUCCEEDED'
export type FETCH_WEATHER_SUCCEEDED = typeof FETCH_WEATHER_SUCCEEDED

export const FETCH_WEATHER_FAIL = 'FETCH_WEATHER_FAIL'
export type FETCH_WEATHER_FAIL = typeof FETCH_WEATHER_FAIL


