//Author-Tejasvi Raj Pant

export const FETCH_WEATHER = 'FETCH_WEATHER'
export type FETCH_WEATHER = typeof FETCH_WEATHER

export const FETCH_WEATHER_REQUESTED = 'FETCH_WEATHER_REQUESTED'
export type FETCH_WEATHER_REQUESTED = typeof FETCH_WEATHER_REQUESTED

export const FETCH_WEATHER_SUCCEEDED = 'FETCH_WEATHER_SUCCEEDED'
export type FETCH_WEATHER_SUCCEEDED = typeof FETCH_WEATHER_SUCCEEDED

export const FETCH_WEATHER_FAIL = 'FETCH_WEATHER_FAIL'
export type FETCH_WEATHER_FAIL = typeof FETCH_WEATHER_FAIL


export const FETCH_LOCATION = 'FETCH_LOCATION'
export type FETCH_LOCATION = typeof FETCH_LOCATION

export const FETCH_LOCATION_REQUESTED = 'FETCH_LOCATION_REQUESTED'
export type FETCH_LOCATION_REQUESTED = typeof FETCH_LOCATION_REQUESTED

export const FETCH_LOCATION_SUCCEEDED = 'FETCH_LOCATION_SUCCEEDED'
export type FETCH_LOCATION_SUCCEEDED = typeof FETCH_LOCATION_SUCCEEDED

export const FETCH_LOCATION_FAIL = 'FETCH_LOCATION_FAIL'
export type FETCH_LOCATION_FAIL = typeof FETCH_LOCATION_FAIL


